#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace UnityVisualStudioSolutionGenerator
{
    /// <summary>
    ///     Provides methods for parsing Visual Studio solution files (.sln or .slnx) and extracting referenced project files.
    /// </summary>
    internal static class SolutionFileParser
    {
        /// <summary>
        ///     Parses the specified <see cref="SolutionFile" /> and gets the project files referenced from the solution.
        /// </summary>
        /// <param name="solutionFile">The solution file to parse.</param>
        /// <param name="onlyIncludeUnityGeneratedProjects">
        ///     Indicates whether to only include project files generated by Unity or files directly inside the solution directory.
        /// </param>
        /// <returns>
        ///     A tuple containing the referenced project files and a flag indicating if the source contains duplicate projects.
        /// </returns>
        internal static (IReadOnlyList<ProjectFile> ProjectFiles, bool SourceContainsDuplicateProjects) Parse(
            SolutionFile solutionFile,
            bool onlyIncludeUnityGeneratedProjects)
        {
            if (solutionFile.IsXmlSolution)
            {
                return XmlSolutionFileParser.Parse(solutionFile, onlyIncludeUnityGeneratedProjects);
            }

            return LegacySolutionFileParser.Parse(solutionFile, onlyIncludeUnityGeneratedProjects);
        }

        /// <summary>
        ///     Parses the solution file content and gets the project files referenced from the solution.
        /// </summary>
        /// <param name="content">The solution file content.</param>
        /// <param name="solutionFile">The solution file being parsed.</param>
        /// <param name="onlyIncludeUnityGeneratedProjects">
        ///     Indicates whether to only include project files generated by Unity or files directly inside the solution directory.
        /// </param>
        /// <returns>
        ///     A tuple containing the referenced project files and a flag indicating if the source contains duplicate projects.
        /// </returns>
        internal static (IReadOnlyList<ProjectFile> ProjectFiles, bool SourceContainsDuplicateProjects) Parse(
            string content,
            SolutionFile solutionFile,
            bool onlyIncludeUnityGeneratedProjects)
        {
            if (solutionFile.IsXmlSolution)
            {
                return XmlSolutionFileParser.Parse(content, solutionFile.SolutionDirectoryPath, onlyIncludeUnityGeneratedProjects);
            }

            return LegacySolutionFileParser.Parse(content, solutionFile.SolutionDirectoryPath, onlyIncludeUnityGeneratedProjects);
        }

        /// <summary>
        ///     Filters and returns the list of project files, optionally including only Unity-generated projects, and indicates if duplicates exist.
        /// </summary>
        /// <param name="solutionDirectoryPath">The absolute directory path of the solution file.</param>
        /// <param name="onlyIncludeUnityGeneratedProjects">
        ///     Indicates whether to only include project files generated by Unity or files directly inside the solution directory.
        /// </param>
        /// <param name="projects">The enumerable of project files to filter.</param>
        /// <returns>
        ///     A tuple containing the filtered project files and a flag indicating if the source contains duplicate projects.
        /// </returns>
        internal static (IReadOnlyList<ProjectFile> ProjectFiles, bool SourceContainsDuplicateProjects) CreateFilteredProjectsResult(
            string solutionDirectoryPath,
            bool onlyIncludeUnityGeneratedProjects,
            IEnumerable<ProjectFile> projects)
        {
            var allProjects = new List<ProjectFile>();
            var sourceContainsDuplicateProjects = false;
            foreach (var projectFile in projects)
            {
                // unity didn't remove the project-entry generated from us from the solution so we need to handle cases where we have duplicate entries
                // one that lies in the solution directory (the one generated by Unity / not changed by us) and one placed next to the .asmdef (generated by us)
                var projectWithSameName = allProjects.FirstOrDefault(project => project.ProjectName == projectFile.ProjectName);
                if (projectWithSameName is not null)
                {
                    if (IsProjectInSolutionDirectory(solutionDirectoryPath, projectFile))
                    {
                        // prefer the one generated by unity (placed in the solution directory)
                        allProjects.Remove(projectFile);
                        allProjects.Add(projectFile);
                        sourceContainsDuplicateProjects = true;
                        continue;
                    }

                    if (IsProjectInSolutionDirectory(solutionDirectoryPath, projectWithSameName))
                    {
                        sourceContainsDuplicateProjects = true;
                        continue;
                    }
                }

                if (onlyIncludeUnityGeneratedProjects && !IsProjectInSolutionDirectory(solutionDirectoryPath, projectFile))
                {
                    continue;
                }

                allProjects.Add(projectFile);
            }

            return (allProjects, sourceContainsDuplicateProjects);
        }

        private static bool IsProjectInSolutionDirectory(string solutionDirectoryPath, ProjectFile projectFile)
        {
            return Path.GetDirectoryName(projectFile.FilePath.AsSpan()).Equals(solutionDirectoryPath, StringComparison.Ordinal);
        }
    }
}
