#nullable enable

using System.Collections.Generic;
using System.IO;
using System.Xml.Linq;

namespace UnityVisualStudioSolutionGenerator
{
    /// <summary>
    ///     Provides methods for parsing Visual Studio solution files in XML format (.slnx).
    /// </summary>
    public static class XmlSolutionFileParser
    {
        /// <summary>
        ///     Parses the XML solution file content and gets the project files referenced from the solution.
        /// </summary>
        /// <param name="content">The XML content of the solution file.</param>
        /// <param name="solutionDirectoryPath">The absolute directory path of the solution file.</param>
        /// <param name="onlyIncludeUnityGeneratedProjects">
        ///     Indicates whether to only include project files generated by Unity or files directly inside the solution directory.
        /// </param>
        /// <returns>
        ///     A tuple containing the referenced project files and a flag indicating if the source contains duplicate projects.
        /// </returns>
        public static (IReadOnlyList<ProjectFile> ProjectFiles, bool SourceContainsDuplicateProjects) Parse(
            string content,
            string solutionDirectoryPath,
            bool onlyIncludeUnityGeneratedProjects)
        {
            var projects = GetUsedProjectFiles(content, solutionDirectoryPath);
            return SolutionFileParser.CreateFilteredProjectsResult(solutionDirectoryPath, onlyIncludeUnityGeneratedProjects, projects);
        }

        /// <summary>
        ///     Parses the specified <see cref="SolutionFile" /> and gets the project files referenced from the solution.
        /// </summary>
        /// <param name="solutionFile">The solution file to parse.</param>
        /// <param name="onlyIncludeUnityGeneratedProjects">
        ///     Indicates whether to only include project files generated by Unity or files directly inside the solution directory.
        /// </param>
        /// <returns>
        ///     A tuple containing the referenced project files and a flag indicating if the source contains duplicate projects.
        /// </returns>
        internal static (IReadOnlyList<ProjectFile> ProjectFiles, bool SourceContainsDuplicateProjects) Parse(
            SolutionFile solutionFile,
            bool onlyIncludeUnityGeneratedProjects)
        {
            return Parse(File.ReadAllText(solutionFile.SolutionFilePath), solutionFile.SolutionDirectoryPath, onlyIncludeUnityGeneratedProjects);
        }

        private static IEnumerable<ProjectFile> GetUsedProjectFiles(string content, string solutionDirectoryPath)
        {
            if (!Directory.Exists(solutionDirectoryPath))
            {
                LogHelper.LogError($"Generating a solution file inside a directory that doesn't exists. Directory path: {solutionDirectoryPath}");
            }

            var document = XDocument.Parse(content);
            foreach (var project in document.Descendants("Project"))
            {
                var projectFileRelativePath = project.Attribute("Path")?.Value;
                if (string.IsNullOrEmpty(projectFileRelativePath))
                {
                    LogHelper.LogError($"Failed to extract csproj file name from Project: {project}");
                    continue;
                }

                var projectFilePath = Path.GetFullPath(projectFileRelativePath, solutionDirectoryPath);
                yield return new ProjectFile(projectFilePath, string.Empty);
            }
        }
    }
}
