name: Update UPM packages
description: Check for updates of any UPM package and update it inside the package.json
inputs:
  project-root-path:
    description: The root path of the Unity project. The folder containing the Assets folder.
    required: true
  excluded-package-patterns:
    required: false
    description: A list of wildcard patterns used to exclude packages from being checked for updates. Each value should be separated by a new line.
    default: |
      com.unity.2d.sprite
      com.unity.modules.*
  package-json-files-to-update:
    required: false
    description: A list of 'package.json' files that should be updated so that its dependency version numbers match the one from the updated packages. Each value should be a path to a 'package.json' file relative to 'project-root-path' separated by a new line.
    default: ""
  github-token:
    required: true
    description: The GitHub token to use for communication with the GitHub API
runs:
  using: composite
  steps:
    - name: Update used package version numbers
      shell: pwsh
      run: >
        & $env:GITHUB_ACTION_PATH/update-upm-packages.ps1
        -ProjectPath '${{ inputs.project-root-path }}'
        -ExcludedPackagePatterns ('${{ inputs.excluded-package-patterns }}'.Split([string[]]@("`n", "`r`n"), [StringSplitOptions]::RemoveEmptyEntries))
        -PackageJsonFilesToUpdate ('${{ inputs.package-json-files-to-update }}'.Split([string[]]@("`n", "`r`n"), [StringSplitOptions]::RemoveEmptyEntries))

    - name: Check changes
      id: check-changes
      shell: pwsh
      run: |
        git diff
        $gitStatus = git status --porcelain
        echo "has-changes=$($gitStatus.Length -ne 0)" >> $env:GITHUB_OUTPUT

    - name: Create Issue with update
      shell: bash
      if: |
        steps.check-changes.outputs.has-changes == 'True'
      run: |
        gh issue create --label "dependencies" --title "Update UPM package dependencies" --repo $GITHUB_REPOSITORY --body "
        ## Diff containing updates:
        ```diff
        $(git diff)
        ```
        "
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
