name: Build and Test

on:
  push:
    branches:
      - "main"
      - "dependabot/github_actions/**"
    tags: ["v*"]
  pull_request_target:
    branches: ["main"]

permissions:
  actions: read
  checks: write
  contents: read
  statuses: write

jobs:
  testOnLinux:
    name: Test on Linux
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request_target' ||
      !startsWith(github.head_ref, 'dependabot/github_actions/')
    steps:
      - name: Checkout only action file
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github/actions/checkout/action.yml
          fetch-depth: 1

      - name: Checkout
        uses: ./.github/actions/checkout

      - name: Unity - Run tests
        uses: game-ci/unity-test-runner@v4.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: src/UnityVisualStudioSolutionGenerator.Tests
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode
